jwt:
  algorithm:
    secret: bread

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client?createDatabaseIfNotExists=true
    username: root
    password: RbzQg1NWrD

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: DEBUG
