jwt:
  algorithm:
    secret: qZWvWjH21KlWC04P6RVfkC2MNC86guOhtQ8nySRC

spring:
  datasource:
    url: jdbc:mysql://db:3306/client?createDatabaseIfNotExist=true
    username: root
    password: RbzQg1NWrD

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: DEBUG

server:
  error:
    include-stacktrace: never
    include-binding-errors: never
